=== neYaANK/semistructured/ex1.dtd
<!-- ex1.dtd -->
<!ELEMENT olympics (sports, description?)>
<!ATTLIST olympics
    year CDATA #REQUIRED
    city CDATA #REQUIRED
>

<!ELEMENT sports (sport+)>

<!ELEMENT sport (name?, teams?, athletes?)>
<!ATTLIST sport
    id ID #REQUIRED
    type CDATA #REQUIRED
>

<!ELEMENT name (#PCDATA)>

<!ELEMENT teams (team+)>
<!ELEMENT team (coach, players)>
<!ATTLIST team
    country CDATA #REQUIRED
>

<!ELEMENT coach (#PCDATA)>

<!ELEMENT players (player+)>
<!ELEMENT player (#PCDATA)>
<!ATTLIST player
    id ID #REQUIRED
    ref IDREF #IMPLIED
>

<!ELEMENT athletes (athlete+)>
<!ELEMENT athlete (name, medals)>
<!ATTLIST athlete
    country CDATA #REQUIRED
>

<!ELEMENT medals (gold, silver, bronze)>
<!ELEMENT gold (#PCDATA)>
<!ELEMENT silver (#PCDATA)>
<!ELEMENT bronze (#PCDATA)>

<!ELEMENT description (#PCDATA | h1 | date)*>
<!ELEMENT h1 (#PCDATA)>
<!ELEMENT date (#PCDATA)>

=== neYaANK/semistructured/ex1-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE olympics SYSTEM "ex1.dtd">

<olympics year="2025" city="Vienna">
    <sports>
        <sport id="S2" type="solo">
            <name>100m Sprint</name>
            <athletes>
                <athlete country="jamaica">
                    <name>Usain Bolt</name>
                    <medals>
                        <gold>3</gold>
                        <silver>0</silver>
                        <bronze>0</bronze>
                    </medals>
                </athlete>
            </athletes>
        </sport>
    </sports>
</olympics>

=== neYaANK/semistructured/ex1/ex1-3-nv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE olympics SYSTEM "ex1.dtd">

<olympics year="2025" city="Vienna">
    <sports>
        <sport sport_id="S3" type="team">
            <name>Baseball</name>
            <teams>
                <team country="france">
                    <coach>John Doe</coach>
                    <players>
                        <player player_id="P2">John Smith</player>
                        <player player_id="P1" ref="P2">Teammate</player>
                    </players>
                </team>
            </teams>
        </sport>
    </sports>
    <!-- <h2> tag is not accepted in mixed element <description>-->
    <description>
        The <h2>Olympics 2025</h2> took place at <date>August 1, 2025</date>.
        They have been around for &gt;100 years already!
    </description>
</olympics>

=== neYaANK/semistructured/ex1-1-nv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE olympics SYSTEM "ex1.dtd">

<olympics year="2025" city="Vienna">
    <sports>
        <sport id="S1" type="team">
            <name>Baseball</name>
            <teams>
                <!-- Team element must contain country attribute -->
                <team>
                    <coach>Felix Bauer</coach>
                    <players>
                        <player id="P1">Stefan Berger</player>
                    </players>
                </team>
            </teams>
        </sport>
    </sports>
</olympics>

=== neYaANK/semistructured/ex1-3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE olympics SYSTEM "ex1.dtd">

<olympics year="2025" city="Vienna">
    <sports>
        <sport id="S3" type="team">
            <name>Baseball</name>
            <teams>
                <team country="france">
                    <coach>John Doe</coach>
                    <players>
                        <player id="P2">John Smith</player>
                        <player id="P1" ref="P2">Teammate</player>
                    </players>
                </team>
            </teams>
        </sport>
    </sports>
    <description>
        The <h1>Olympics 2025</h1> took place at <date>August 1, 2025</date>.
        They have been around for &gt;100 years already!
    </description>
</olympics>

=== neYaANK/semistructured/ex1/ex1-2-nv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE olympics SYSTEM "ex1.dtd">

<olympics year="2025" city="Vienna">
    <sports>
        <sport sport_id="S2" type="solo">
            <name>100m Sprint</name>
            <athletes>
                <athlete country="jamaica">
                    <!-- Name element accepts no child elements -->
                    <!-- First and last elements are not defined -->
                    <name>
                        <first>Usain</first>
                        <last>Bolt</last>
                    </name>
                    <medals>
                        <gold>3</gold>
                        <silver>0</silver>
                        <bronze>0</bronze>
                    </medals>
                </athlete>
            </athletes>
        </sport>
    </sports>
</olympics>

=== neYaANK/semistructured/ex1/ex1-1-nv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE olympics SYSTEM "ex1.dtd">

<olympics year="2025" city="Vienna">
    <sports>
        <sport sport_id="S1" type="team">
            <name>Baseball</name>
            <teams>
                <!-- Team element must contain country attribute -->
                <team>
                    <coach>Felix Bauer</coach>
                    <players>
                        <player player_id="P1">Stefan Berger</player>
                    </players>
                </team>
            </teams>
        </sport>
    </sports>
</olympics>
